import React, { useEffect, useState } from "react";
import { PieChart, Pie, Cell, ResponsiveContainer, LineChart, Line, YAxis, Tooltip as RTooltip } from "recharts";
import { C, grad } from "../theme";
import { Card, SectionTitle } from "../components/ui";
import { ATTENDANCE } from "../data/mockData";
import { apiGet } from "../api";

export function AttendancePage() {
  const [attendance, setAttendance] = useState(ATTENDANCE);
  useEffect(() => { apiGet("/attendance?student_id=1", null).then(data => { if (Array.isArray(data) && data.length) { const total = data.reduce((s,x)=>s+Number(x.total_classes||0),0); const attended=data.reduce((s,x)=>s+Number(x.attended_classes||0),0); const overall=total ? Number((attended/total*100).toFixed(2)) : 0; setAttendance({ overall, present: attended, absent: total-attended, late: 0, subjects:data.map(x=>({name:x.subject,pct:Number(x.attendance_percentage||0)})), trend:[overall,overall,overall,overall] }); } }); }, []);
  const donutData=[{name:"Present",value:attendance.overall},{name:"Remaining",value:100-attendance.overall}]; const trendData=attendance.trend.map((v,i)=>({name:`W${i+1}`,v}));
  return <div className="p-4 lg:p-6"><SectionTitle title="Attendance Overview" subtitle="Track your attendance across every subject." /><div className="grid lg:grid-cols-3 gap-4 mb-4"><Card className="p-5 flex flex-col items-center justify-center"><div className="relative w-[150px] h-[150px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={donutData} dataKey="value" innerRadius={54} outerRadius={70} startAngle={90} endAngle={-270} stroke="none"><Cell fill="#22C55E"/><Cell fill="rgba(255,255,255,0.07)"/></Pie></PieChart></ResponsiveContainer><div className="absolute inset-0 flex flex-col items-center justify-center"><div className="text-[24px] font-semibold" style={{color:C.text}}>{attendance.overall}%</div><div className="text-[10.5px]" style={{color:C.faint}}>Overall</div></div></div><div className="mt-3 text-[12.5px] font-medium" style={{color:C.green}}>Good standing</div><div className="text-[11.5px] text-center mt-1" style={{color:C.faint}}>You are above the minimum attendance requirement</div></Card><Card className="p-5 lg:col-span-2"><SectionTitle title="Subject-wise Attendance"/><div className="space-y-3.5">{attendance.subjects.map(s=><div key={s.name}><div className="flex justify-between text-[12.5px] mb-1.5"><span style={{color:C.text}}>{s.name}</span><span style={{color:s.pct<80?"#FFC069":C.sub}} className="font-medium">{s.pct}%</span></div><div className="h-2 rounded-full w-full" style={{background:"rgba(255,255,255,0.06)"}}><div className="h-2 rounded-full" style={{width:`${s.pct}%`,background:s.pct<80?"linear-gradient(90deg,#F5A524,#FFC069)":grad}}/></div></div>)}</div></Card></div><div className="grid lg:grid-cols-3 gap-4"><Card className="p-5 lg:col-span-2"><SectionTitle title="Monthly Trend"/><div className="h-40"><ResponsiveContainer width="100%" height="100%"><LineChart data={trendData}><YAxis hide domain={[70,95]}/><RTooltip contentStyle={{background:C.panel2,border:`1px solid ${C.border}`,borderRadius:10,fontSize:12}} labelStyle={{color:C.sub}}/><Line type="monotone" dataKey="v" stroke="#8B5CF6" strokeWidth={2.5} dot={{r:3,fill:"#8B5CF6"}}/></LineChart></ResponsiveContainer></div></Card><Card className="p-5"><SectionTitle title="Statistics"/><div className="space-y-3">{[{label:"Present",value:attendance.present,color:C.green},{label:"Absent",value:attendance.absent,color:C.red},{label:"Late",value:attendance.late,color:C.amber}].map(s=><div key={s.label} className="flex items-center justify-between"><span className="flex items-center gap-2 text-[12.5px]" style={{color:C.sub}}><span className="w-2 h-2 rounded-full" style={{background:s.color}}/>{s.label}</span><span className="text-[13.5px] font-semibold" style={{color:C.text}}>{s.value}</span></div>)}</div></Card></div></div>;
}
