import React, { useEffect, useState } from "react";
import { Mail, Phone, MapPin, Pencil } from "lucide-react";
import { C } from "../theme";
import { Card, Badge, SectionTitle, PrimaryButton, GhostButton, Avatar } from "../components/ui";
import { STUDENT } from "../data/mockData";
import { apiGet, apiRequest } from "../api";

export function ProfilePage({ showToast }) {
  const [editing, setEditing] = useState(false);
  const [data, setData] = useState(STUDENT);
  const [draft, setDraft] = useState(STUDENT);
  useEffect(() => { apiGet("/profile?student_id=1", null).then((value) => { if (value && !Array.isArray(value)) { const mapped = { ...STUDENT, ...value, studentId: value.studentId || value.student_id, program: value.program || STUDENT.program }; setData(mapped); setDraft(mapped); } }); }, []);
  const save = async () => { try { const updated = await apiRequest("/profile?student_id=1", { method: "PUT", body: JSON.stringify({ email: draft.email, phone: draft.phone, address: draft.address }) }); const next = { ...data, ...draft, ...(updated || {}) }; setData(next); setDraft(next); setEditing(false); showToast("Profile updated"); } catch { setData(draft); setEditing(false); showToast("Profile updated locally"); } };
  const field = (label, key, icon) => <div><label className="text-[11.5px] font-medium flex items-center gap-1.5 mb-1.5" style={{ color: C.faint }}>{icon}{label}</label>{editing ? <input value={draft[key] || ""} onChange={(e) => setDraft({ ...draft, [key]: e.target.value })} className="w-full rounded-lg px-3 py-2 text-[13px] outline-none" style={{ background: "#0B1120", border: `1px solid ${C.border}`, color: C.text }} /> : <div className="text-[13.5px]" style={{ color: C.text }}>{data[key]}</div>}</div>;
  return <div className="p-4 lg:p-6"><SectionTitle title="Student Profile" /><Card className="p-5 mb-4"><div className="flex items-start justify-between mb-5"><div className="flex items-center gap-4"><Avatar size={64} /><div><div className="text-[16px] font-semibold" style={{ color: C.text }}>{data.name}</div><div className="text-[12.5px]" style={{ color: C.faint }}>{data.program?.split(",")[0]} · {data.semester}</div><div className="text-[11.5px] mt-1" style={{ color: C.faint }}>Student ID: {data.studentId}</div><Badge tone="submitted">{data.status}</Badge></div></div>{editing ? <PrimaryButton onClick={save}>Save</PrimaryButton> : <GhostButton onClick={() => { setDraft(data); setEditing(true); }}><Pencil size={13} className="inline mr-1.5 -mt-0.5" />Edit Profile</GhostButton>}</div><div className="text-[12.5px] font-semibold mb-3" style={{ color: C.sub }}>Contact Information</div><div className="grid sm:grid-cols-2 gap-4 mb-5">{field("Email", "email", <Mail size={12} />)}{field("Phone", "phone", <Phone size={12} />)}{field("Address", "address", <MapPin size={12} />)}</div></Card><Card className="p-5"><div className="text-[12.5px] font-semibold mb-3" style={{ color: C.sub }}>Academic Information</div><div className="grid sm:grid-cols-3 gap-4"><div><div className="text-[11.5px] mb-1" style={{ color: C.faint }}>Branch</div><div className="text-[13.5px]" style={{ color: C.text }}>Computer Science & Engineering</div></div><div><div className="text-[11.5px] mb-1" style={{ color: C.faint }}>Semester</div><div className="text-[13.5px]" style={{ color: C.text }}>{data.semester}</div></div><div><div className="text-[11.5px] mb-1" style={{ color: C.faint }}>Batch</div><div className="text-[13.5px]" style={{ color: C.text }}>{data.batch}</div></div></div></Card></div>;
}
